# -*- coding: utf-8 -*-
"""Visualização De Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-D9kBr9_RcGjFt_1a-G2RccEjYac43J
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt

# %matplotlib inline
import matplotlib.pyplot as plt
dados = open("populacao_brasileira.csv").readlines()


x = []
y = []

for i in range(len(dados)):
  if i != 0:
    linha = dados[i].split(";")
    x.append(int(linha[0]))
    y.append(int(linha[1]))
    plt.scatter(x,y)
    plt.bar(x,y, color = "b")
    plt.plot(x,y, color ="r")
    plt.title("Crescimento da População Brasileira 1980-2016")
    plt.xlabel("Ano")
    plt.ylabel("População x 100.000.000")
    plt.savefig("Popullacao_brasileira.png")

"""# Nova seção"""